// src/utils/constants.js

export const TRANSLATIONS = {
  zh: {
    title: 'AlphaQuant Pro',
    sidebarToggle: '切换侧边栏',
    currentStock: '当前标的',
    runBacktest: '运行回测',
    running: '计算中...',
    
    // --- 侧边栏标题 (新) ---
    sectionData: '数据源配置',
    sectionStock: '标的与时间',
    sectionPlan: '交易执行方案', 
    sectionStrategy: '核心策略模型',

    // --- 数据源 ---
    dataSourceTushare: 'Tushare API',
    dataSourceBaostock: 'Baostock',
    dataSourceMock: '模拟数据',
    inputToken: '输入 Token...',
    manualImport: '手动导入 JSON',
    imported: '已导入数据',
    
    // --- 标的 ---
    selectStock: '选择股票',
    customCode: '-- 自定义代码 --',
    startDate: '开始日期',
    endDate: '结束日期',
    
    // --- 交易执行方案 (Plan) ---
    positionSize: '单笔仓位限制', 
    stopLoss: '止损线 (Stop-Loss)',
    takeProfit: '止盈线 (Take-Profit)',
    trendFilter: '大势过滤器 (MA60)',
    trendFilterOn: '开启：顺势而为',
    trendFilterOff: '关闭：所有信号',
    riskOff: '不启用',
    
    // --- 方案说明书 ---
    viewPlanGuide: '查看方案说明书',
    planGuideTitle: '交易执行方案详解',
    planPosTitle: '1. 单笔仓位限制 (Position Sizing)',
    planPosDesc: '鸡蛋不要放在一个篮子里。如果设为 30%，代表你有 10万 本金，每次最多只拿 3万 去买这只股票，剩下的钱留着避险。',
    planStopTitle: '2. 止损线 (Stop Loss)',
    planStopDesc: '保命神器。如果买入后跌幅达到了设定值（比如 -5%），系统会无脑强制卖出，防止小亏变大亏。',
    planTakeTitle: '3. 止盈线 (Take Profit)',
    planTakeDesc: '落袋为安。如果买入后涨幅达到了设定值（比如 +20%），系统会强制卖出止盈，防止赚到的钱又跌回去。',
    planTrendTitle: '4. 大势过滤器 (Trend Filter)',
    planTrendDesc: '不接飞刀。开启后，只有当股价在 60日均线（生命线）上方时才允许买入。这能帮你自动躲过 2022 年那种单边下跌的熊市。',
    
    // --- 策略参数 ---
    strategyBoll: '布林带策略',
    strategyMacd: 'MACD策略',
    paramPeriod: '周期 (Period)',
    paramMultiplier: '带宽 (StdDev)',
    paramShort: '快线 (Short)',
    paramLong: '慢线 (Long)',
    paramSignal: '信号 (Signal)',
    initialCapital: '初始本金',
    viewStrategy: '查看策略逻辑',

    totalReturn: '总收益率',
    maxDrawdown: '最大回撤',
    winRate: '交易胜率',
    finalEquity: '最终资产',
    chartVolume: '成交量',
    tabChart: 'K线与指标',
    tabEquity: '收益曲线',
    tabTrades: '交易明细',
    tableDate: '日期',
    tableType: '方向',
    tablePrice: '价格',
    tableShares: '股数',
    tableReason: '信号依据',
    noTrades: '此策略参数下无交易信号触发',
    startPrompt: '请点击右上角“运行回测”开始分析',
    typeBuy: '买入',
    typeSell: '卖出',
    typeStopLoss: '止损',
    typeTakeProfit: '止盈',
    loadingData: '正在计算策略...',
    copyScript: '复制 Python 脚本',
    copySuccess: '已复制',
    step1: '第一步：复制 Python 脚本',
    step2: '第二步：粘贴运行结果',
    pastePlaceholder: '在此处粘贴 Python 脚本运行输出的 JSON 数据...',
    loadAndRun: '加载数据并回测',
    scriptHintBao: '需 pip install baostock pandas',
    scriptHintTu: '需 pip install tushare',
    strategyLogic: '策略逻辑详解',
    
    reasonBollBuy: (p) => `股价(${p}) 触及下轨`,
    reasonBollSell: (p) => `股价(${p}) 触及上轨`,
    reasonMacdGold: 'MACD金叉 (DIF上穿DEA)',
    reasonMacdDeath: 'MACD死叉 (DIF下穿DEA)',
    reasonStopLoss: (p) => `触发止损 (现价 ${p})`,
    reasonTakeProfit: (p) => `触发止盈 (现价 ${p})`,
    reasonTrendBlock: '趋势向下 (MA60压制)，放弃买入',

    bollTitle: '布林带均值回归策略',
    bollDesc: '基于统计学原理，假设股价始终围绕均线波动。',
    bollBuy: '买入信号：股价跌破下轨 (Lower Band)，大概率反弹。',
    bollSell: '卖出信号：股价突破上轨 (Upper Band)，大概率回调。',
    bollScene: '适用场景：震荡市、箱体整理行情。',
    
    macdTitle: 'MACD 趋势跟踪策略',
    macdDesc: '经典的趋势指标，用于捕捉大级别的上涨或下跌。',
    macdBuy: '金叉买入：快线 (DIF) 上穿 慢线 (DEA)。',
    macdSell: '死叉卖出：快线 (DIF) 下穿 慢线 (DEA)。',
    macdScene: '适用场景：单边趋势行情 (牛市/熊市)。'
  },
  en: {
    title: 'AlphaQuant Pro',
    sidebarToggle: 'Toggle Sidebar',
    currentStock: 'Stock',
    runBacktest: 'Run Backtest',
    running: 'Running...',
    
    sectionData: 'Data Source',
    sectionStock: 'Stock & Date',
    sectionPlan: 'Execution Plan',
    sectionStrategy: 'Strategy Model',

    dataSourceTushare: 'Tushare API',
    dataSourceBaostock: 'Baostock',
    dataSourceMock: 'Simulation',
    inputToken: 'Enter Token...',
    manualImport: 'Import JSON',
    imported: 'Data Imported',
    
    selectStock: 'Select Stock',
    customCode: '-- Custom Code --',
    startDate: 'Start Date',
    endDate: 'End Date',
    
    positionSize: 'Position Size',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    trendFilter: 'Trend Filter',
    trendFilterOn: 'On: Above MA60',
    trendFilterOff: 'Off: All Signals',
    riskOff: 'Disabled',

    viewPlanGuide: 'View Execution Guide',
    planGuideTitle: 'Execution Plan Guide',
    planPosTitle: '1. Position Sizing',
    planPosDesc: 'Risk control. If set to 30%, you only invest 30% of your total cash into this trade, keeping the rest safe.',
    planStopTitle: '2. Stop Loss',
    planStopDesc: 'Protection. Automatically sells if price drops by X% to prevent catastrophic losses.',
    planTakeTitle: '3. Take Profit',
    planTakeDesc: 'Secure gains. Automatically sells if price rises by X% to lock in your profit.',
    planTrendTitle: '4. Trend Filter (MA60)',
    planTrendDesc: 'Don\'t catch falling knives. If ON, the system only buys when price is ABOVE the 60-day average line (Bull Market trend).',

    strategyBoll: 'Bollinger Bands',
    strategyMacd: 'MACD Trend',
    paramPeriod: 'Period',
    paramMultiplier: 'StdDev',
    paramShort: 'Short',
    paramLong: 'Long',
    paramSignal: 'Signal',
    initialCapital: 'Initial Capital',
    viewStrategy: 'Strategy Details',

    totalReturn: 'Total Return',
    maxDrawdown: 'Max Drawdown',
    winRate: 'Win Rate',
    finalEquity: 'Final Equity',
    chartVolume: 'Volume',
    tabChart: 'Chart',
    tabEquity: 'Equity Curve',
    tabTrades: 'Trade Log',
    tableDate: 'Date',
    tableType: 'Side',
    tablePrice: 'Price',
    tableShares: 'Shares',
    tableReason: 'Signal Reason',
    noTrades: 'No trades triggered with current parameters.',
    startPrompt: 'Click "Run Backtest" to start analysis.',
    typeBuy: 'Buy',
    typeSell: 'Sell',
    typeStopLoss: 'Stop Loss',
    typeTakeProfit: 'Take Profit',
    loadingData: 'Processing Strategy...',
    copyScript: 'Copy Python Script',
    copySuccess: 'Copied!',
    step1: 'Step 1: Copy Python Script',
    step2: 'Step 2: Paste Output JSON',
    pastePlaceholder: 'Paste the JSON output from the Python script here...',
    loadAndRun: 'Load Data & Run',
    scriptHintBao: 'Requires: pip install baostock pandas',
    scriptHintTu: 'Requires: pip install tushare',
    strategyLogic: 'Strategy Logic',

    reasonBollBuy: (p) => `Price (${p}) touched Lower Band`,
    reasonBollSell: (p) => `Price (${p}) touched Upper Band`,
    reasonMacdGold: 'MACD Golden Cross',
    reasonMacdDeath: 'MACD Death Cross',
    reasonStopLoss: (p) => `Stop Loss Triggered (${p})`,
    reasonTakeProfit: (p) => `Take Profit Triggered (${p})`,
    reasonTrendBlock: 'Trend Down (Below MA60), Skip Buy',

    bollTitle: 'Bollinger Bands (Mean Reversion)',
    bollDesc: 'Based on statistics, assuming price oscillates around the mean.',
    bollBuy: 'Buy Signal: Price breaks below Lower Band.',
    bollSell: 'Sell Signal: Price breaks below Lower Band.',
    bollScene: 'Best for: Oscillating markets, sideways trends.',
    
    macdTitle: 'MACD (Trend Following)',
    macdDesc: 'Classic indicator to capture major market trends.',
    macdBuy: 'Golden Cross: DIF crosses above DEA.',
    macdSell: 'Death Cross: DIF crosses below DEA.',
    macdScene: 'Best for: Trending markets (Bull/Bear runs).'
  }
};

export const STOCK_PROFILES = {
  '600519': { name: '贵州茅台', nameEn: 'Kweichow Moutai', ts_code: '600519.SH', startPrice: 1800, volatility: 0.015, trend: 0.0002 },
  '300750': { name: '宁德时代', nameEn: 'CATL', ts_code: '300750.SZ', startPrice: 200, volatility: 0.035, trend: 0.0005 },
  '000001': { name: '平安银行', nameEn: 'Ping An Bank', ts_code: '000001.SZ', startPrice: 15, volatility: 0.02, trend: 0.0001 },
  '601127': { name: '赛力斯', nameEn: 'Seres Group', ts_code: '601127.SH', startPrice: 80, volatility: 0.05, trend: 0.001 },
};